### ISSUE TITLE
Occlusion query crash

### ISSUE THREAD

**Issue by TheCyberBrick** [Angry-Pixel/The-Betweenlands#185]
Is anybody else getting this crash?
Looks like it's happening due to an out of bounds error during the occlusion query on this line (403):
"this.worldRenderers[(j1 * this.renderChunksTall + i1) * this.renderChunksWide + l].glOcclusionQuery = this.glOcclusionQueryBase.get(k);"
in RenderGlobal#loadRenderers().

Stack trace:
at java.nio.Buffer.checkIndex(Buffer.java:540)
at java.nio.DirectIntBufferU.get(DirectIntBufferU.java:253)
at net.minecraft.client.renderer.RenderGlobal.func_72712_a(RenderGlobal.java:350)
at net.minecraft.client.renderer.RenderGlobal.func_72732_a(RenderGlobal.java:294)
at net.minecraft.client.Minecraft.func_71353_a(Minecraft.java:2216)
at net.minecraft.client.Minecraft.func_71403_a(Minecraft.java:2146)
at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:240)
at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:70)
at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:13)
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2061)
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
at net.minecraft.client.main.Main.main(SourceFile:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by vadis365** [comment]
Hello,
I have had that error even without the BL, Erebus or any other mods except Forge. It seems to be associated with render distance. If you lower the render distance it will stop it. It could be a Forge thing - tbh I don't know.
Cheers,
Me.

**Comment by TheCyberBrick** [comment]
Ah good to know, thank you :)
