### ISSUE TITLE
Obfuscated field needs fixing

### ISSUE THREAD

**Issue by TheCyberBrick** [Angry-Pixel/The-Betweenlands#218]
This needs fixing:

cpw.mods.fml.relauncher.ReflectionHelper$UnableToFindFieldException: java.lang.NoSuchFieldException: currentFrustum
 at cpw.mods.fml.relauncher.ReflectionHelper.findField(ReflectionHelper.java:94) ~[forgeSrc-1.7.10-10.13.4.1558-1.7.10.jar:?]
 at thebetweenlands.client.render.ConnectionRenderer.<init>(ConnectionRenderer.java:43) ~[The-Betweenlands/:?]
 at thebetweenlands.proxy.ClientProxy.init(ClientProxy.java:287) ~[The-Betweenlands/:?]
 at thebetweenlands.TheBetweenlands.init(TheBetweenlands.java:139) ~[The-Betweenlands/:?]

**Comment by TheCyberBrick** [comment]
nvm
