### ISSUE TITLE
Renderer Crash

### ISSUE THREAD

**Issue by Zsashas** [Angry-Pixel/The-Betweenlands#251]
https://gist.github.com/Zsashas/9b16124799a37cded6ee3d0ae4a3ca22

Only happens with The Betweenlands present in the modlist.

**Comment by vadis365** [comment]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/EntityRenderer
at com.emoniph.witchery.Witchery.preInit(Witchery.java:177)

This would suggest that Witchery was to blame for doing something with the EntityRender
That crash is usually due to a client method being called on the server side - could you also please report it to the Witchery mod as it may be something cross mod causing it.

**Comment by Zsashas** [comment]
Reported to Witchery & awaiting response. I still believe this to be a TBL issue however. No issues with this before, even with past Betweenlands versions. And Witchery hasn't updated in forever.

**Comment by pau101** [comment]
@Zsashas I'd like you to run the game with these JVM arguments
-Dlegacy.debugClassLoading=true
-Dlegacy.debugClassLoadingFiner=true
And then post `logs/fml-client-latest.log`

**Comment by Zsashas** [comment]
https://gist.githubusercontent.com/Zsashas/5bf82cdf635091a6f4f4513e4fa6030a/raw/966de133c7765fdd6ccd54c7f64575e136fd1935/gistfile1.txt

Wow, that's long.

**Comment by pau101** [comment]
So the problem arises from DragonAPI, Witchery was just the first to try to load the EntityRenderer.
[This](http://pastebin.com/raw/KmRamQB5) is the crash I'm working with now. Just have to look into what DragonAPI is trying to do and then I'll try to find a way for it to still work with BL.

**Comment by ReikaKalseki** [comment]
It is an ASM conflict into getMouseOver. I add a Forge event so that I can change the mouseover. You appear to do so as well.

**Comment by ShadesRaith** [comment]
I'm running between lands alone and I have received this when I am in the Realm for around 47 to 89 seconds.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  TheBetweenlandsLoadingPlugin (TheBetweenlands-2.0.2-alpha-universal.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 4/21/17 8:47 AM
Description: Tesselating block model

java.lang.OutOfMemoryError: Tesselating block model
	at sun.misc.Unsafe.allocateMemory(Native Method)
	at java.nio.DirectByteBuffer.<init>(Unknown Source)
	at java.nio.ByteBuffer.allocateDirect(Unknown Source)
	at net.minecraft.client.renderer.GLAllocation.func_74524_c(SourceFile:41)
	at net.minecraft.client.renderer.VertexBuffer.func_181670_b(VertexBuffer.java:55)
	at net.minecraft.client.renderer.VertexBuffer.func_178981_a(VertexBuffer.java:421)
	at net.minecraftforge.client.model.pipeline.VertexBufferConsumer.put(VertexBufferConsumer.java:65)
	at net.minecraftforge.client.model.pipeline.VertexLighterFlat.processQuad(VertexLighterFlat.java:210)
	at net.minecraftforge.client.model.pipeline.QuadGatheringTransformer.put(QuadGatheringTransformer.java:63)
	at net.minecraftforge.client.model.pipeline.UnpackedBakedQuad.pipe(UnpackedBakedQuad.java:85)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.render(ForgeBlockModelRenderer.java:124)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187497_c(ForgeBlockModelRenderer.java:82)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:46)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:37)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:81)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:199)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:43)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at sun.misc.Unsafe.allocateMemory(Native Method)
	at java.nio.DirectByteBuffer.<init>(Unknown Source)
	at java.nio.ByteBuffer.allocateDirect(Unknown Source)
	at net.minecraft.client.renderer.GLAllocation.func_74524_c(SourceFile:41)
	at net.minecraft.client.renderer.VertexBuffer.func_181670_b(VertexBuffer.java:55)
	at net.minecraft.client.renderer.VertexBuffer.func_178981_a(VertexBuffer.java:421)
	at net.minecraftforge.client.model.pipeline.VertexBufferConsumer.put(VertexBufferConsumer.java:65)
	at net.minecraftforge.client.model.pipeline.VertexLighterFlat.processQuad(VertexLighterFlat.java:210)
	at net.minecraftforge.client.model.pipeline.QuadGatheringTransformer.put(QuadGatheringTransformer.java:63)
	at net.minecraftforge.client.model.pipeline.UnpackedBakedQuad.pipe(UnpackedBakedQuad.java:85)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.render(ForgeBlockModelRenderer.java:124)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187497_c(ForgeBlockModelRenderer.java:82)

-- Block model being tesselated --
Details:
	Block: thebetweenlands:swamp_plant
	Block location: World: (414,121,569), Chunk: (at 14,7,9 in 25,35; contains blocks 400,0,560 to 415,255,575), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
	Using AO: false
Stacktrace:
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:46)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:37)

-- Block being tesselated --
Details:
	Block type: ID #407 (tile.thebetweenlands.swampPlant // null)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (414,121,569), Chunk: (at 14,7,9 in 25,35; contains blocks 400,0,560 to 415,255,575), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
Stacktrace:
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:81)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['ShadesRaith'/405, l='MpServer', x=321.98, y=121.00, z=642.59]]
	Chunk stats: MultiplayerChunkCache: 353, 353
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (128,64,248), Chunk: (at 0,4,8 in 8,15; contains blocks 128,0,240 to 143,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 64814 game time, 34252 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: ~~ERROR~~ ConcurrentModificationException: null
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:49)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_111, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 98730256 bytes (94 MB) / 1037959168 bytes (989 MB) up to 1037959168 bytes (989 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -Xms1G
	IntCache: cache: 0, tcache: 0, allocated: 1, tallocated: 18
	FML: MCP 9.32 Powered by Forge 12.18.3.2281 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2281.jar) 
	UCHIJAAAA	Forge{12.18.3.2281} [Minecraft Forge] (forge-1.10.2-12.18.3.2281.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCHIJAAAA	thebetweenlands{2.0.2-alpha} [The Betweenlands] (TheBetweenlands-2.0.2-alpha-universal.jar) 
	Loaded coremods (and transformers): 
TheBetweenlandsLoadingPlugin (TheBetweenlands-2.0.2-alpha-universal.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Launched Version: 1.10.2-forge1.10.2-12.18.3.2281
	LWJGL: 2.9.4
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 6x AMD FX(tm)-6300 Six-Core Processor

**Comment by ReikaKalseki** [comment]
Your error has **nothing** to do with this issue.
