### ISSUE TITLE
Crash after eating weeping blue pettles

### ISSUE THREAD

**Issue by purpleposeidon** [Angry-Pixel/The-Betweenlands#277]
java.lang.ArrayIndexOutOfBoundsException: -32
        at net.minecraft.potion.PotionEffect.func_76455_a(PotionEffect.java:105)
        at net.minecraft.entity.EntityLivingBase.func_70679_bo(EntityLivingBase.java:524)
        at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:293)
        at net.minecraft.entity.Entity.func_70071_h_(Entity.java:318)
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1561)
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288)
        at net.minecraft.client.entity.EntityClientPlayerMP.func_70071_h_(SourceFile:63)
        at net.minecraft.world.World.func_72866_a(World.java:2070)
        at net.minecraft.world.World.func_72870_g(World.java:2034)
        at net.minecraft.world.World.func_72939_s(World.java:1887)
        at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006)
        at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
        at net.minecraft.client.main.Main.main(SourceFile:148)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by TheCyberBrick** [comment]
Did you have any other mods installed that add potions? We made the potion IDs configurable just recently in https://github.com/Angry-Pixel/The-Betweenlands/commit/8fa1ce2fbffa7d037c9b9138aa1cde59716e1212
That might fix it.

**Comment by purpleposeidon** [comment]
Yes, Thaumcraft adds potions.

Got a similar crash falling into some kind of black decay liquid (tar?), and then compiled 7e94669. It's probably safe to say it's fixed.
