### ISSUE TITLE
Shading Error when generating Betweenlands

### ISSUE THREAD

**Issue by MidnightsFX** [Angry-Pixel/The-Betweenlands#294]
Got this error when loading the Betweenlands.

```
[20:07:25] [Client thread/INFO] [STDERR/]: [thebetweenlands.client.render.shader.ShaderHelper:enableShader:89]: Failed loading shader files!
[20:07:25] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: net.minecraft.client.util.JsonException: Invalid shaders/program/blshader.fsh: Couldn't compile fragment program: Fragment shader failed to compile with the following errors:
ERROR: 0:4: error(#102) #error: Macro begin with GL_ is reserved
ERROR: 0:5: error(#102) #error: Macro begin with GL_ is reserved
ERROR: error(#273) 2 compilation errors.  No code generated
[20:07:25] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.shader.ShaderLoader.func_148057_a(SourceFile:67)
[20:07:25] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.shader.ShaderManager.<init>(SourceFile:130)
[20:07:25] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.shader.Shader.<init>(SourceFile:26)
[20:07:25] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at thebetweenlands.client.render.shader.base.CShaderInt.<init>(CShaderInt.java:57)
[20:07:25] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at thebetweenlands.client.render.shader.base.CShaderGroup.func_148023_a(CShaderGroup.java:48)
[20:07:25] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.shader.ShaderGroup.func_152764_a(SourceFile:136)
[20:07:25] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.shader.ShaderGroup.func_152765_a(SourceFile:84)
[20:07:25] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at thebetweenlands.client.render.shader.base.CShaderGroup.func_152765_a(CShaderGroup.java:43)
[20:07:25] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.shader.ShaderGroup.<init>(SourceFile:50)
[20:07:25] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at thebetweenlands.client.render.shader.base.CShaderGroup.<init>(CShaderGroup.java:26)
[20:07:25] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at thebetweenlands.client.render.shader.base.CShader.getShaderGroup(CShader.java:75)
[20:07:25] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at thebetweenlands.client.render.shader.ShaderHelper.enableShader(ShaderHelper.java:80)
[20:07:25] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at thebetweenlands.event.render.ShaderHandler.onRenderHand(ShaderHandler.java:52)
[20:07:25] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.eventhandler.ASMEventHandler_519_ShaderHandler_onRenderHand_RenderHandEvent.invoke(.dynamic)
[20:07:25] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[20:07:25] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
[20:07:25] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraftforge.client.ForgeHooksClient.renderFirstPersonHand(ForgeHooksClient.java:266)
[20:07:25] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.GeneratedMethodAccessor29.invoke(Unknown Source)
[20:07:25] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:07:25] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:483)
[20:07:25] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at Reflector.callBoolean(Reflector.java:222)
[20:07:25] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1755)
[20:07:25] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1330)
[20:07:25] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
[20:07:25] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
[20:07:25] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.main.Main.main(SourceFile:148)
[20:07:25] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:07:25] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:07:25] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:07:25] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:483)
[20:07:25] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[20:07:25] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[20:07:25] [Client thread/DEBUG] [CustomOreGen/]: Client world changed to MpServer
[20:09:05] [Thread-21/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NullPointerException
[20:09:05] [Thread-21/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.jcraft.jogg.StreamState.packetout(StreamState.java:186)
[20:09:05] [Thread-21/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at paulscode.sound.codecs.CodecJOrbis.readBytes(CodecJOrbis.java:575)
[20:09:05] [Thread-21/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at paulscode.sound.codecs.CodecJOrbis.read(CodecJOrbis.java:354)
[20:09:05] [Thread-21/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at paulscode.sound.Source.stream(Source.java:953)
[20:09:05] [Thread-21/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at paulscode.sound.StreamThread.run(StreamThread.java:129)
```

I am running a number of other mods, and can re-test this to determine if this is directly related to this mod or a combination. If you need that. Otherwise I am happy to provide some more clarification if you need. Thanks!

**Comment by TheCyberBrick** [comment]
This was fixed in d8d89d7981fcc35720a1400fbcc46741fbde7e1d

**Comment by MidnightsFX** [comment]
Sweet thanks! Sorry I did not look in closed issues. When would it be reasonable to expect the next build?

**Comment by TheCyberBrick** [comment]
Probably pretty soon, maybe this weekend
